name: verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-selinuxd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       almalinux : ["8"]
    container:
      image: almalinux:${{ matrix.almalinux }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: yum -y --enablerepo=powertools install golang make libsemanage-devel diffutils
      - name: run verify
        run: |
          make verify
